uLearn/Models/NavigationLink.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace uLearn.Models
{
    public class NavigationLink
    {
        public string Text { get; set; } 
        public string Url { get; set; }
        public bool NewWindow { get; set; }
        public string Target { get { return NewWindow ? "_blank" : null; } }
        public string Title { get; set; }

        public NavigationLink()
        { }

        public NavigationLink(string url, string text = null, bool newWindow = false, string title = null)
        {
            Text = text;
            Url = url;
            NewWindow = newWindow;
            Title = title;
        }
    }
}

uLearn/Models/NavigationListItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace uLearn.Models
{
    public class NavigationListItem
    {
        public string Text { get; set; }
        public NavigationLink Link { get; set; }
        public List<NavigationListItem> Items { get; set; }
        public bool HasChildren { get { return Items != null && Items.Any() && Items.Count > 0; } }

        public NavigationListItem()
        { }

        public NavigationListItem(NavigationLink link)
        {
            Link = link;
        }

        public NavigationListItem(string text)
        {
            Text = text;
        }
    }
}

uLearn/Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;
using uLearn.Models;

namespace uLearn.Controller
{
    public class SiteLayoutController : SurfaceController
    {
        public const string VIEW_FOLDER_PATH = "~/Views/Partials/SiteLayout/";

        /// <summary>
        /// Renders the top navigation partial
        /// </summary>
        /// <returns>Partial view with a model</returns>
        public ActionResult RenderHeader()
        {
            List<NavigationListItem> nav = GetNavigationModelFromDatabase();
            return PartialView(VIEW_FOLDER_PATH + "_TopNavigation.cshtml", nav);
        }

        /// <summary>
        /// Finds the home page and gets the navigation structure based on it and it's children
        /// </summary>
        /// <returns>A List of NavigationListItems, representing the structure of the site.</returns>
        private List<NavigationListItem> GetNavigationModelFromDatabase()
        {
            const int HOME_PAGE_POSITION_IN_PATH = 1;
            int homePageId = int.Parse(CurrentPage.Path.Split(',')[HOME_PAGE_POSITION_IN_PATH]);
            IPublishedContent homePage = Umbraco.Content(homePageId);
            // 3 lines above generate bug, home page is outside of array - Left in intentionally
            List<NavigationListItem> nav = new List<NavigationListItem>();
            nav.Add(new NavigationListItem(new NavigationLink(homePage.Url, homePage.Name)));
            nav.AddRange(GetChildNavigationList(homePage));
            return nav;
        }

        /// <summary>
        /// Loops through the child pages of a given page and their children to get the structure of the site.
        /// </summary>
        /// <param name="page">The parent page which you want the child structure for</param>
        /// <returns>A List of NavigationListItems, representing the structure of the pages below a page.</returns>
        private List<NavigationListItem> GetChildNavigationList(dynamic page)
        {
            List<NavigationListItem> listItems = null;
            var childPages = page.Children.Where("Visible");
            if (childPages != null && childPages.Any() && childPages.Count() > 0)
            {
                listItems = new List<NavigationListItem>();
                foreach (var childPage in childPages)
                {
                    NavigationListItem listItem = new NavigationListItem(new NavigationLink(childPage.Url, childPage.Name));
                    listItem.Items = GetChildNavigationList(childPage);
                    listItems.Add(listItem);
                }
            }
            return listItems;
        }
    }
}

uLearn/Views/ContactUs.cshtml
@using Umbraco.Core.Models
@using Umbraco.Web
@using Umbraco.Web.Mvc
@using ContentModels = Umbraco.Web.PublishedContentModels;


@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@{
    Layout = "Webbase.cshtml";
}

@*Render partials for banners and nested content*@

@Html.Partial("~/Views/Partials/Banner/BannerPicker.cshtml", Model.Content)

@Html.Partial("~/Views/Partials/Nested/NestedPicker.cshtml", Model.Content)

@*Option - true/false to determine whether to show sidebar || Remove else <p> once testing is finished*@

@{
    if ((Model.Content.GetPropertyValue<bool>("Optional")) == true)
    {
        @Html.Partial("~/Views/Partials/Sidebar.cshtml", Model.Content)
    }
    else
    {
        <p>Sidebar switched off! <em>- This is here for testing and will be deleted once finished</em></p>
    }
}


@*Forms need fixed - renders even when not selected*@
@Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid="767267c4-d309-4519-af4e-06612f59a16a", FormTheme="", ExcludeScripts="0"}) 

uLearn/Views/ContentPage.cshtml
@using Umbraco.Core.Models
@using Umbraco.Web
@using Umbraco.Web.Mvc
@using ContentModels = Umbraco.Web.PublishedContentModels;


@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@{
    Layout = "Webbase.cshtml";
}

@Html.Partial("~/Views/Partials/Banner/BannerPicker.cshtml", Model.Content)

@Html.Partial("~/Views/Partials/Carousel/CarouselPicker.cshtml", Model.Content)

@Html.Partial("~/Views/Partials/Nested/NestedPicker.cshtml", Model.Content)

@Html.Partial("~/Views/Partials/Accordion/AccordionPicker.cshtml", Model.Content)

@{
    if ((Model.Content.GetPropertyValue<bool>("Optional")) == true)
    {
        @Html.Partial("~/Views/Partials/Sidebar.cshtml", Model.Content)
    }
    else
    {
        <p>sidebar option turned off - Remove text after testing</p>
    }
}

uLearn/Views/Home.cshtml
@using Umbraco.Core.Models
@using Umbraco.Web
@using Umbraco.Web.Mvc
@using ContentModels = Umbraco.Web.PublishedContentModels;


@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@{
    Layout = "Webbase.cshtml";
}

@Html.Partial("~/Views/Partials/Banner/BannerPicker.cshtml", Model.Content)

@Html.Partial("~/Views/Partials/Carousel/CarouselPicker.cshtml", Model.Content)

@Html.Partial("~/Views/Partials/Nested/NestedPicker.cshtml", Model.Content)

@{
    if ((Model.Content.GetPropertyValue<bool>("Optional")) == true)
    {
        @Html.Partial("~/Views/Partials/Sidebar.cshtml", Model.Content)
    }
    else
    {
        <p>This is here for testing and will be deleted once finished</p>
    }
}

@*Question for Dave - The sidebar above, is it correct to put the if statement here or would it be better to run the if statement within the partial?*@

@Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid="767267c4-d309-4519-af4e-06612f59a16a", FormTheme="", ExcludeScripts="0"})

uLearn/Views/Import.cshtml
@using Umbraco.Core.Models;
@using Umbraco.Web;
@using Umbraco.Web.Mvc;
@using ContentModels = Umbraco.Web.PublishedContentModels;


@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@{
    Layout = "Webbase.cshtml";

    var imgid = Umbraco.Field("image");
    var imgurl = Umbraco.Media(imgid.ToString()).Url;
}

<i>The text below this has been imported</i>

<h1>@Umbraco.Field("title")</h1>
@Umbraco.Field("text")

@Html.Partial("~/Views/Partials/Banner/BannerPicker.cshtml", Model.Content)

@Umbraco.Field("date")<br />
 

<img src="@imgurl" alt="">
@Umbraco.Field("image")

uLearn/Views/MacroPartials/InsertUmbracoFormWithTheme.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
	
@if (Model.MacroParameters["FormGuid"] != null)
{
    var s = Model.MacroParameters["FormGuid"].ToString();
    var theme = "";
    var includeScripts = true;

    @*
        If a theme is provided as a macro parameter, forms will attempt to use custom theme files
        ex: given the value "test", forms will look up views for the form and fields in a custom directory:

        Form will be rendered with
            /Views/Partials/Forms/Themes/test/form.cshml

        Fields will be rendered with
            /Views/Partials/Forms/Themes/test/FieldType/[fieldtypename].cshtml

        If a file is not available in the custom directory, forms will fallback to the default files in
            /Views/Partials/Forms/Themes/default/
    *@

    if(Model.MacroParameters.ContainsKey("FormTheme"))
    {
        theme = Model.MacroParameters["FormTheme"].ToString();
    }

    if (Model.MacroParameters.ContainsKey("ExcludeScripts"))
    {

        @*
            Inverse the boolean - RenderAction Parameter expects it to be false for exclusion
            But with default value for Macro Paramater boolean/checkbox being false 
            We want to ensure by default we include the scripts next to the form
        *@
        includeScripts = Model.MacroParameters["ExcludeScripts"].ToString() == "0";
    }

    var form = new Guid(s);
    var recordGuid = Guid.Empty;

    if (string.IsNullOrEmpty(Request.QueryString["recordId"]) == false)
    {
        Guid.TryParse(Request.QueryString["recordId"], out recordGuid);
    }

    Html.RenderAction("RenderForm", "UmbracoForms", new {formId = form, recordId = recordGuid, theme = theme, includeScripts = includeScripts });
}

uLearn/Views/MacroPartials/RenderUmbracoFormScripts.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Forms.Web.Controllers
@{
    var formsToRender = new List<Guid>();
    object forms = TempData["UmbracoForms"];
    if (forms != null)
    {
        formsToRender = (List<Guid>)forms;
    }

    // Reading TempData["UmbracoForms"] should have set it to null but this doesn't
    // happen if this request didn't return a 200 OK status. https://stackoverflow.com/a/7630709/5018
    // Explictly clear it so that on the next request the scripts don't get rendered.
    TempData.Remove("UmbracoForms");
}

@foreach (Guid form in formsToRender)
{
    Html.RenderAction("Render", "UmbracoForms", new { formId = form, mode = "script" });
}

uLearn/Views/Partials/Carousel/CarouselImageTitle.cshtml
@model CarouselImageTitle

<br />
<img src="@Model.Image.Url" alt="Oh god help" />
@Model.Title <br />

uLearn/Views/Partials/Carousel/CarouselPicker.cshtml
@using Umbraco.Web;
@inherits UmbracoViewPage<IPublishedContent>

@{
    var items = Model.GetPropertyValue<IEnumerable<IPublishedContent>>("Carousel");

    if (items != null)
    {
        foreach (var item in items)
        {
            if (item is CarouselImageTitle)
            {
                @Html.Partial("~/Views/Partials/Carousel/CarouselImageTitle.cshtml", new CarouselImageTitle(item))
            }
        }
    }
}

uLearn/Views/Partials/Forms/Export/csv.cshtml
@model Umbraco.Forms.Web.Models.Backoffice.EntrySearchResultCollection
@foreach (var header in Model.schema)
{<text>"</text>@Html.Raw(header.Name)<text>",</text>}

@foreach (var row in Model.Results)
{
    foreach (var col in row.Fields)
    {<text>"</text>@Html.Raw(col).ToString().Replace(Environment.NewLine, " ")<text>",</text>}

    @Environment.NewLine
}

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.CheckBox.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel    
<input type="checkbox" name="@Model.Name" id="@Model.Id" 
    @if(Model.Mandatory){<text>  data-val="true" data-val-requiredcb="@Model.RequiredErrorMessage"</text>}
    @if (Model.ContainsValue(true) || Model.ContainsValue("true") || Model.ContainsValue("on"))
    {<text>checked="checked"</text>}       
                                                                                                         
    />

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.CheckBoxList.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@{ var i = 0; }
          
<span class="checkboxlist" id="@Model.Id">
@foreach (Umbraco.Forms.Mvc.Models.PrevalueViewModel pv in Model.PreValues)  
{
    <input type="checkbox" name="@Model.Name" id="@string.Concat(Model.Id,"_",i)" value="@pv.Value" 
    @if (Model.Mandatory) {<text>data-val="true" data-val-requiredlist="@Model.RequiredErrorMessage"</text>}
    @if (Model.ContainsValue(pv.Value)){<text>checked="checked"</text>}/>
    
    <label for="@string.Concat(Model.Id,"_",i)">@pv.Value</label>
    <br />

    i++;
}
</span>

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.DatePicker.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel        
@{
    string val = string.Empty;
    if (Model.ValueAsObject != null && Model.ValueAsObject != "")
    {
        try
        {
            DateTime d;
            d = (DateTime) Model.ValueAsObject;
            val = d.ToShortDateString();
        }
        catch (Exception ex)
        {
            val = Model.ValueAsObject.ToString();
        }
    }
}

<input type="hidden" name="@Model.Name" id="@Model.Id" class="datepickerfieldshadow" value="@val" />
<input type="text" name="@Model.Name" id="@(Model.Id)_1" class="datepickerfield" value="@val" @{if (Model.Mandatory) { <text> data-val="true" data-val-required="@Model.RequiredErrorMessage" </text> }} />

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.DropDownList.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<select name="@Model.Name" id="@Model.Id"
@if (Model.Mandatory){<text> data-val="true" data-val-required="@Model.RequiredErrorMessage"</text>}
>
    <option value=""></option>
    @foreach (var pv in Model.PreValues)
    {
        <option value="@pv.Value" 
        @if (Model.ContainsValue(pv.Value))
        {<text>selected="selected"</text>}
        >@pv.Value</option>
    }
</select>

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.FileUpload.cshtml
@using Umbraco.Web
@model Umbraco.Forms.Mvc.Models.FieldViewModel

<input type="file" name="@Model.Name" id="@Model.Id" multiple
@if(Model.Mandatory){<text> data-val="true" data-val-required="@Model.RequiredErrorMessage"</text>} />

@if (Model.Values != null && Model.Values.Any())
{
    <p>
        <strong>Current File/s:</strong><br/>
        @foreach (Dictionary<string, string> dictionaryObject in Model.Values)
        {
            @*
            The model.values contains a list of dictionary objects with a single item
            With the key being the full path to the file
            And the value being the filename
            *@
            if (dictionaryObject.Count > 0)
            {
                var fileInfo = dictionaryObject.First();
                <a href="@fileInfo.Key" target="_blank">@fileInfo.Value</a><br/>
                <input type="hidden" name="@(Model.Name)_file_@(fileInfo.Value)" value="@fileInfo.Key" />
            }
        }
    </p>
}

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.HiddenField.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<input type="hidden" name="@Model.Name" id="@Model.Id" class="hidden" value="@Model.ValueAsHtmlString"/>

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.PasswordField.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<input type="password" name="@Model.Name" id="@Model.Id" class="text" value="@Model.ValueAsHtmlString"
@{if(string.IsNullOrEmpty(Model.PlaceholderText) == false){<text>placeholder="@Model.PlaceholderText"</text>}}
@{if(Model.Mandatory || Model.Validate){<text>data-val="true"</text>}}
@{if (Model.Mandatory) {<text> data-val-required="@Model.RequiredErrorMessage"</text>}}
@{if (Model.Validate) {<text> data-val-regex="@Model.InvalidErrorMessage" data-regex="@Model.Regex"</text>}}
/>

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.RadioButtonList.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel    
@{ var i = 0; }
   
<span class="radiobuttonlist" id="@Model.Id">
@foreach (Umbraco.Forms.Mvc.Models.PrevalueViewModel pv in Model.PreValues)  
{
    <input type="radio" name="@Model.Id" id="@string.Concat(Model.Id,"_",i)" value="@pv.Value" 
    @if (Model.Mandatory) {<text>data-val="true" data-val-requiredlist="@Model.RequiredErrorMessage"</text>}
    @if (Model.ContainsValue(pv.Value)){<text>checked="checked"</text>} />
    <label for="@string.Concat(Model.Id,"_",i)">@pv.Value</label>
    <br />
    
    i++;
}
</span>

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.Text.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@using Umbraco.Forms.Core.Extensions

@{
    var settings = Model.AdditionalSettings;
    var hasCaption = (settings.ContainsKey("Caption") && !string.IsNullOrEmpty(settings["Caption"]));
    var hasBody = (settings.ContainsKey("BodyText") && !string.IsNullOrEmpty(settings["BodyText"]));
}

<div id="@Model.Id">
    @if (hasCaption)
    {
        <h2>@settings["Caption"].ParsePlaceHolders()</h2>
    }
    @if (hasBody)
    {
        <p>@Html.Raw(settings["BodyText"].ParsePlaceHolders().Replace(System.Environment.NewLine, "<br />"))</p>
    }
</div>

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.Textarea.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<textarea name="@Model.Name" id="@Model.Id" rows="2" cols="20"
@{if(string.IsNullOrEmpty(Model.PlaceholderText) == false){<text>placeholder="@Model.PlaceholderText"</text>}}
@{if(Model.Mandatory || Model.Validate){<text>data-val="true"</text>}}
@{if (Model.Mandatory) {<text> data-val-required="@Model.RequiredErrorMessage"</text>}}
@{if (Model.Validate) {<text> data-val-regex="@Model.InvalidErrorMessage" data-regex="@Html.Raw(Model.Regex)"</text>}}
>@Model.ValueAsHtmlString</textarea>

uLearn/Views/Partials/Forms/Fieldtypes/FieldType.Textfield.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<input type="text" name="@Model.Name" id="@Model.Id" class="text" value="@Model.ValueAsHtmlString" maxlength="500"
@{if(string.IsNullOrEmpty(Model.PlaceholderText) == false){<text>placeholder="@Model.PlaceholderText"</text>}}
@{if(Model.Mandatory || Model.Validate){<text>data-val="true"</text>}}
@{if (Model.Mandatory) {<text> data-val-required="@Model.RequiredErrorMessage"</text>}}
@{if (Model.Validate) {<text> data-val-regex="@Model.InvalidErrorMessage" data-regex="@Html.Raw(Model.Regex)"</text>}}
/>

uLearn/Views/Partials/Forms/Fieldtypes/Fieldtype.Recaptcha.cshtml
@using System.Runtime.CompilerServices
@using Umbraco.Forms.Mvc.Helpers
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@{
    var theme = "clean";
    if (Model.AdditionalSettings.Any(x => x.Key == "Theme"))
    {
        theme = Model.AdditionalSettings.FirstOrDefault(x => x.Key == "Theme").Value;
    }
}
@ReCaptchaHelper.ReCaptcha(theme)

uLearn/Views/Partials/Forms/Fieldtypes/Fieldtype.Recaptcha2.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
@{
    var siteKey = Umbraco.Forms.Core.Configuration.GetSetting("RecaptchaPublicKey");
    var theme = "clean";
    var themeSetting = Model.AdditionalSettings.FirstOrDefault(x => x.Key == "Theme");
    if (themeSetting.Value != "")
    {
        theme = themeSetting.Value;
    }
    var size = "normal";
    var sizeSetting = Model.AdditionalSettings.FirstOrDefault(x => x.Key == "Size");
    if (sizeSetting.Value != "")
    {
        size = sizeSetting.Value;
    }

    if (!string.IsNullOrEmpty(siteKey))
    {
        <script src="https://www.google.com/recaptcha/api.js" async defer></script>
        <div class="g-recaptcha" data-sitekey="@siteKey" data-theme="@theme" data-size="@size"></div>
    }
    else
    {
        <p class="error">ERROR: ReCaptcha v.2 is missing the Site Key - Please update the web.config to include 'key="RecaptchaSiteKey"'</p>
    }
}

uLearn/Views/Partials/Forms/Themes/bootstrap3-horizontal/Form.cshtml
@inherits WebViewPage<FormViewModel>
@using Umbraco.Forms.Core
@using Umbraco.Forms.Mvc
@using Umbraco.Forms.Mvc.Models
@using Umbraco.Forms.Mvc.BusinessLogic

@*Set a default class on all fields - needed by bootstrap*@
@Html.SetFormFieldClass("form-control")

@* Wrap all fields in a form-group - needed by bootstrap to correctly display fields horizontally*@
@Html.SetFormFieldWrapperClass("form-group")


<div class="umbraco-forms-page form-horizontal">

    @if (string.IsNullOrEmpty(Model.CurrentPage.Caption) == false)
    {
        <h4 class="umbraco-forms-caption">@Model.CurrentPage.Caption</h4>
    }
                
    @if (Model.ShowValidationSummary)
    {
        @Html.ValidationSummary(false)
    }

    @foreach (FieldsetViewModel fs in Model.CurrentPage.Fieldsets)
    {

    <fieldset class="umbraco-forms-fieldset" id="@fs.Id">

        @if (string.IsNullOrEmpty(fs.Caption) == false)
        {
            <legend>@fs.Caption</legend>
        }

        <div class="row-fluid">

            @foreach (var c in fs.Containers)
            {
                <div class="umbraco-forms-container @("col-md-" + c.Width)">

                    @foreach (FieldViewModel f in c.Fields)
                    {
                        bool hidden = f.HasCondition && f.ConditionActionType == FieldConditionActionType.Show;

                        <div class="@Html.GetFormFieldWrapperClass(f.FieldTypeName)  @f.CssClass" @{ if (hidden) { <text> style="display: none" </text>  } }>

                            @if (!f.HideLabel)
                            {
                                <label for="@f.Id" class="col-sm-2 control-label umbraco-forms-label">
                                    @f.Caption 
                                    @if (f.ShowIndicator)
                                    {
                                        <span class="umbracoForms-Indicator">@Model.Indicator</span>
                                    }
                                </label>
                            }

                            <div class="col-sm-10 umbraco-forms-field-wrapper">

                                @Html.Partial(FormThemeResolver.GetFieldView(Model, f), f)

                                @if (Model.ShowFieldValidaton)
                                {
                                    @Html.ValidationMessage(f.Id)
                                }

                                @if (!string.IsNullOrEmpty(f.ToolTip))
                                {
                                    <p class="help-block">@f.ToolTip</p>
                                }
                            </div>


                        </div>
                    }

                </div>

            }
        </div>

    </fieldset>

    }


    <div style="display: none">
        <input type="text" name="@Model.FormId.ToString().Replace("-", "")" />
    </div>

		
    <div class="umbraco-forms-navigation row-fluid">
		
        <div class="col-sm-10 col-sm-offset-2">
            @if (Model.IsMultiPage)
            {
                if (!Model.IsFirstPage)
                {
                    <input class="btn prev cancel" type="submit" value="@Model.PreviousCaption" name="__prev"/>
                }
                if (!Model.IsLastPage)
                {
                    <input type="submit" class="btn next" value="@Model.NextCaption" name="next"/>
                }
                if (Model.IsLastPage)
                {
                    <input type="submit" class="btn primary" value="@Model.SubmitCaption" name="submitbtn"/>
                }
            }
            else
            {
                <input type="submit" class="btn btn-primary" value="@Model.SubmitCaption" name="submitbtn"/>
            }
        </div>


    </div>

</div>

uLearn/Views/Partials/Sidebar.cshtml
@using Umbraco.Web
@using Umbraco.Web.Routing
@inherits UmbracoViewPage<IPublishedContent>

<h2>Sidebar</h2>

@{

    <ul>
        @foreach (var child in Model.Children)
        {
            <li><a href="@child.Id">@child.Name</a></li>
        }
    </ul>

}

uLearn/Views/Partials/SiteLayout/_Footer.cshtml
@inherits UmbracoViewPage

@Umbraco.Field("footerTitle", insertBefore: "<h3>", insertAfter: "</h3>")
@Umbraco.Field("footerContent")

uLearn/Views/Partials/SiteLayout/_MainNav.cshtml
@inherits UmbracoViewPage

    <div><a href="home">Test Project<span>.</span></a></div>
    <ul>
        <li><a href="home">Home</a></li>
        <li><a href="blog">Blog</a></li>
        <li><a href="content">Content</a></li>
    </ul>













@*@inherits Umbraco.Web.Mvc.UmbracoViewPage<List<NavigationListItem>>
@using uLearn.Models

<nav role="navigation">
    <ul>
        @RenderChildItems(Model)
    </ul>
</nav>



@helper RenderChildItems(List<NavigationListItem> listItems)
{
    if (listItems != null)
    {
        foreach (var item in listItems)
        {
            <li>
                @if (!String.IsNullOrEmpty(item.Text))
                {
                    @item.Text
                }
                else if (item.Link != null)
                {
                    <a href="@item.Link.Url" class="@(Umbraco.AssignedContentItem.Url == item.Link.Url ? "active" : null) @(item.HasChildren ? "fh5co-sub-ddown" : null)" target="@item.Link.Target">@item.Link.Text</a>
                }

                @if (item.HasChildren)
                {
                    <ul class="sub-menu">
                        @RenderChildItems(item.Items)
                    </ul>
                }
            </li>
        }
    }
}

*@

uLearn/Views/Partials/Text/SubtitleBase.cshtml
@model SubtitleBase

<h2>@Model.Subtitle</h2>

uLearn/Views/Partials/Text/TextBase150.cshtml
@model TextBase150

@Model.Text <br />

uLearn/Views/Partials/Text/TextBase50.cshtml
@model TextBase50
   
@Model.Text <br />

uLearn/Views/Partials/Text/TextBase500.cshtml
@model TextBase500

@Model.Text <br />

uLearn/Views/Partials/Text/TextBaseRich.cshtml
@model TextBaseRich

@Model.Text <br />

uLearn/Views/Partials/Text/TitleBase.cshtml
@model TitleBase

<h1>@Model.Title</h1>

uLearn/Views/PersonalisedPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Webbase.cshtml";
}

@* the fun starts here *@

@Umbraco.Field("title")

@Html.Partial("~/Views/Partials/Banner/BannerPicker.cshtml", Model.Content)

uLearn/Views/WebBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

@Html.Partial("~/Views/Partials/SiteLayout/_MainNav.cshtml")

@*@Html.RenderAction("RenderHeader", "SiteLayout");                 Dynamic nav code attempt left in intentionally - Need to know whats wrong/how to fix*@
@RenderBody()